
package com.evry.employee.resources;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeResource", targetNamespace = "http://resources.employee.evry.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeResource {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.evry.employee.resources.EmployeeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.UpdateEmployeeResponse")
    public EmployeeEntity updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeEntity arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.evry.employee.resources.EmployeeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.GetEmployeeResponse")
    public EmployeeEntity getEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.evry.employee.resources.EmployeeEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.GetAllEmployeesResponse")
    public List<EmployeeEntity> getAllEmployees();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.evry.employee.resources.EmployeeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.AddEmployeeResponse")
    public EmployeeEntity addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeEntity arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.evry.employee.resources.EmployeeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.LoginResponse")
    public EmployeeEntity login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://resources.employee.evry.com/", className = "com.evry.employee.resources.DeleteEmployeeResponse")
    public void deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
