
package com.evry.employee.resources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeResourceImplService", targetNamespace = "http://resources.employee.evry.com/", wsdlLocation = "http://localhost:8085/api/service?wsdl")
public class EmployeeResourceImplService
    extends Service
{

    private final static URL EMPLOYEERESOURCEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEERESOURCEIMPLSERVICE_EXCEPTION;
    private final static QName EMPLOYEERESOURCEIMPLSERVICE_QNAME = new QName("http://resources.employee.evry.com/", "EmployeeResourceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/api/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEERESOURCEIMPLSERVICE_WSDL_LOCATION = url;
        EMPLOYEERESOURCEIMPLSERVICE_EXCEPTION = e;
    }

    public EmployeeResourceImplService() {
        super(__getWsdlLocation(), EMPLOYEERESOURCEIMPLSERVICE_QNAME);
    }

    public EmployeeResourceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEERESOURCEIMPLSERVICE_QNAME, features);
    }

    public EmployeeResourceImplService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEERESOURCEIMPLSERVICE_QNAME);
    }

    public EmployeeResourceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEERESOURCEIMPLSERVICE_QNAME, features);
    }

    public EmployeeResourceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeResourceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeResource
     */
    @WebEndpoint(name = "EmployeeResourceImplPort")
    public EmployeeResource getEmployeeResourceImplPort() {
        return super.getPort(new QName("http://resources.employee.evry.com/", "EmployeeResourceImplPort"), EmployeeResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeResource
     */
    @WebEndpoint(name = "EmployeeResourceImplPort")
    public EmployeeResource getEmployeeResourceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resources.employee.evry.com/", "EmployeeResourceImplPort"), EmployeeResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEERESOURCEIMPLSERVICE_EXCEPTION!= null) {
            throw EMPLOYEERESOURCEIMPLSERVICE_EXCEPTION;
        }
        return EMPLOYEERESOURCEIMPLSERVICE_WSDL_LOCATION;
    }

}
